config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root 'top#index' 

 post 'update_stock' => 'top#update_stock'
 post 'update_tracking' => 'top#update_tracking'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  self.table_name = 'cscart_orders'
  self.primary_key = :order_id

  has_many :order_details
  has_many :states, primary_key: :s_state, foreign_key: :code
  has_many :wayo_orders_extensions, foreign_key: :order_id

  scope :during_yesterday, -> { where(timestamp: [Time.now.yesterday.beginning_of_day.to_i..Time.now.yesterday.end_of_day.to_i]) }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  self.table_name = 'cscart_order_details'
  self.primary_key = :item_id

  belongs_to :order
  belongs_to :product_description, foreign_key: :product_id
end

app/models/product.rb
class Product < ApplicationRecord
  self.table_name = 'cscart_products'
  self.primary_key = :product_id

  has_many :product_options_inventories
end

app/models/product_description.rb
class ProductDescription < ApplicationRecord
  self.table_name = 'cscart_product_descriptions'
  self.primary_key = :product_id

  has_many :order_details
end

app/models/product_options_inventory.rb
class ProductOptionsInventory < ApplicationRecord
  self.table_name = 'cscart_product_options_inventory'
  self.primary_key = :product_code
end

app/models/state.rb
class State < ApplicationRecord
  self.table_name = 'cscart_states'
  self.primary_key = :state_id

  has_many :orders
  has_many :state_descriptions
end

app/models/state_description.rb
class StateDescription < ApplicationRecord
  self.table_name = 'cscart_state_descriptions'
  self.primary_key = :state_id

  has_many :states
end

app/models/wayo_orders_extension.rb
class WayoOrdersExtension < ApplicationRecord
  self.table_name = 'cscart_wayo_orders_extension'
  self.primary_key = :order_id

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def update_stock
    UpdateStockJob.perform_now(params[:file])
    redirect_to root_path, notice: '処理が終了しました'
  end

  def update_stock
    UpdateTrackingJob.perform_now(params[:file])
    redirect_to root_path, notice: '処理が終了しました'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WayoBatch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash.present? %>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "row alert alert-#{key}") %>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>

<%= form_tag(update_stock_path, method: "post", multipart: true) do %>
  <%= file_field_tag :file %>
  <%= submit_tag "在庫情報更新" %>
<% end %>

<%= form_tag(update_tracking_path, method: "post", multipart: true) do %>
  <%= file_field_tag :file %>
  <%= submit_tag "トラッキング情報更新" %>
<% end %>